### ISSUE TITLE
为了你的帐号安全，此微信号不能登录网页微信

### ISSUE THREAD

**Issue by lcycode** [yangxuanxc/wechat_friends#39]
运行get_user_info.py 扫码登录报错，Keystroke: 'skey'，该怎么处理？

**Comment by yangxuanxc** [comment]
部分微信号不支持登录，只有申请得比较早的账号可行。

**Comment by yangxuanxc** [comment]
> 运行get_user_info.py 扫码登录报错，Keystroke: 'skey'，该怎么处理？

部分微信号不支持登录，只有申请得比较早的账号可行。

**Comment by yangxuanxc** [comment]
部分微信号不支持登录，只有申请得比较早的账号可行。
